name: recipetap
description: RecipeTap.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^1.0.0+5
  clay_containers: ^0.2.2
  cloud_firestore: ^0.13.5
  concentric_transition: ^0.1.1
  cupertino_icons: ^0.1.3
  custom_refresh_indicator: null
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.16.0
  firebase_core: ^0.4.4+3
  firebase_messaging: ^6.0.16
  flare_flutter: ^2.0.3
  flutter_brand_icons: ^1.1.0
  flutter_full_pdf_viewer: ^1.0.6
  flutter_spinkit: ^4.1.2+1
  flutter_sticky_header: ^0.4.2
  flutter_swiper: ^1.1.6
  google_nav_bar: ^2.2.0
  google_sign_in: ^4.5.1
  html: ^0.14.0+3
  http: ^0.12.1
  native_updater: ^0.0.3
  path_provider: ^1.6.9
  pdf: ^1.8.1
  permission_handler: ^5.0.0+hotfix.6
  provider: ^4.1.2
  readmore: ^1.0.0
  share_extend: ^1.1.5
  shared_preferences: ^0.5.7+3
  sliver_fab: ^1.0.0
  timeago: ^2.0.26
  url_launcher: ^5.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/.
    - assets/flare/.
    - assets/images/categories/.
    - assets/images/timesofday/.
    - assets/logo/.
    - assets/onboarding/.
    - assets/ice_cream_indicator/.
    #   - images/a_dot_ham.jpeg
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets
    # -and-images/#resolution-aware.
    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Playlist.ttf
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
